import {createClient} from 'jsr:@supabase/supabase-js@2.116.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'x-egg-token','Access-Control-Allow-Methods':'GET,OPTIONS'};
const J=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const S=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const enc=new TextEncoder();async function hash(v:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(v)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='GET')return J({error:'Método inválido.'},405);try{const s=S(),token=req.headers.get('x-egg-token')||'';if(!token)return J({error:'Entre na sua conta.'},401);const {data:ss}=await s.from('egg_sessions').select('user_id,expires_at').eq('token_hash',await hash(token)).maybeSingle();if(!ss||new Date(ss.expires_at)<=new Date())return J({error:'Entre na sua conta.'},401);const uid=ss.user_id;
const tables=[['egg_purchases','Ovo Feliz'],['life_purchases','Vida Feliz'],['shop_purchases','Minha Lojinha'],['super_purchases','Super Capacidade']];
const games=(await Promise.all(tables.map(async([table,game])=>{const {data,error}=await s.from(table).select('item_type,item_id,amount_cents,status,paid_at,created_at').eq('user_id',uid);if(error){const {data:alternate}=await s.from(table).select('item_id,amount_cents,status,paid_at,created_at').eq('user_id',uid);return (alternate||[]).filter((x:any)=>x.status==='paid'||!!x.paid_at).map((x:any)=>({game,item:String(x.item_id||'Compra'),amount_cents:x.amount_cents,paid_at:x.paid_at||x.created_at}))}return (data||[]).filter((x:any)=>x.status==='paid'||!!x.paid_at).map((x:any)=>({game,item:String(x.item_type||x.item_id||'Compra'),amount_cents:x.amount_cents,paid_at:x.paid_at||x.created_at}))}))).flat().sort((a:any,b:any)=>+new Date(b.paid_at)-+new Date(a.paid_at));
const [{data:en},{data:courseRows}]=await Promise.all([s.from('course_enrollments').select('course_id,enrolled_at').eq('user_id',uid),s.from('courses').select('id,title,slug')]);const cm=new Map((courseRows||[]).map((c:any)=>[c.id,c]));return J({games,courses:(en||[]).map((e:any)=>({...cm.get(e.course_id),enrolled_at:e.enrolled_at}))})
}catch(e){console.error(e);return J({error:'Não foi possível carregar a conta.'},500)}});
