import {createClient} from 'jsr:@supabase/supabase-js@2.116.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const S=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const enc=new TextEncoder();
const hex=(a:ArrayBuffer)=>[...new Uint8Array(a)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function passHash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:160000},key,256))}
async function reveal(value:string){if(!value)return '';const keyData=await crypto.subtle.digest('SHA-256',enc.encode('dominael-recovery-v1:'+Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'))),key=await crypto.subtle.importKey('raw',keyData,'AES-GCM',false,['decrypt']);const [a,b]=value.split('.'),bytes=(v:string)=>Uint8Array.from(atob(v),x=>x.charCodeAt(0));return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(a)},key,bytes(b)))}
async function audit(s:any,u:any,action:string){const{error}=await s.from('account_audit').insert({user_id:u.id,username:u.username,actor:'admin',action});if(error)throw error}
async function A(req:Request){const s=S(),t=(req.headers.get('Authorization')||'').replace('Bearer ','');const {data:{user}}=await s.auth.getUser(t);if(!user)throw Error('AUTH');const {data:a}=await s.from('admins').select('user_id').eq('user_id',user.id).maybeSingle();if(!a)throw Error('AUTH');return s}
const paid=(x:any)=>['paid','approved','completed','confirmed','generated'].includes(String(x?.status||'').toLowerCase())||!!x?.paid_at;
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const s=await A(req);
if(req.method==='GET'){const [{data:users},{data:coursePurch},{data:eggPurch},{data:lifePurch},{data:genJobs},{data:courses},{data:eggPackages},{data:eggItems},{data:lifePackages},{data:lifeItems},{data:genTypes}]=await Promise.all([
s.from('egg_users').select('id,username,email,full_name,recovery_birth_cipher,recovery_grand_cipher,created_at,last_seen_at').order('created_at',{ascending:false}),
s.from('course_purchases').select('user_id,course_id,amount_cents,status,paid_at,created_at'),
s.from('egg_purchases').select('user_id,item_type,item_id,amount_cents,status,paid_at,created_at'),
s.from('life_purchases').select('user_id,item_type,item_id,amount_cents,status,paid_at,created_at'),
s.from('generator_jobs').select('user_id,generator_type_id,amount_cents,status,paid_at,created_at'),
s.from('courses').select('id,title'),s.from('egg_coin_packages').select('id,label'),s.from('egg_gold_items').select('id,name'),s.from('life_coin_packages').select('id,label'),s.from('life_shop_items').select('id,name'),s.from('generator_types').select('id,name')]);
const cm=new Map((courses||[]).map((x:any)=>[x.id,x.title])),ep=new Map((eggPackages||[]).map((x:any)=>[String(x.id),x.label])),ei=new Map((eggItems||[]).map((x:any)=>[String(x.id),x.name])),lp=new Map((lifePackages||[]).map((x:any)=>[String(x.id),x.label])),li=new Map((lifeItems||[]).map((x:any)=>[String(x.id),x.name])),gm=new Map((genTypes||[]).map((x:any)=>[String(x.id),x.name]));
const details=new Map<string,any[]>();const add=(uid:string,d:any)=>{if(!uid)return;const a=details.get(uid)||[];a.push(d);details.set(uid,a)};
for(const x of coursePurch||[])if(paid(x))add(x.user_id,{area:'Cursos',item:cm.get(x.course_id)||'Curso',amount_cents:Number(x.amount_cents||0),date:x.paid_at||x.created_at});
for(const x of eggPurch||[])if(paid(x))add(x.user_id,{area:'Ovo Feliz',item:x.item_type==='coins'?(ep.get(String(x.item_id))||'Pacote de moedas'):(ei.get(String(x.item_id))||String(x.item_id||'Item')),amount_cents:Number(x.amount_cents||0),date:x.paid_at||x.created_at});
for(const x of lifePurch||[])if(paid(x))add(x.user_id,{area:'Vida Feliz',item:x.item_type==='coins'?(lp.get(String(x.item_id))||'Pacote de moedas'):(li.get(String(x.item_id))||String(x.item_id||'Item')),amount_cents:Number(x.amount_cents||0),date:x.paid_at||x.created_at});
for(const x of genJobs||[])if(paid(x))add(x.user_id,{area:'Geradores',item:gm.get(String(x.generator_type_id))||'Gerador',amount_cents:Number(x.amount_cents||0),date:x.paid_at||x.created_at});
const rows=await Promise.all((users||[]).map(async(u:any)=>{const d=(details.get(u.id)||[]).sort((a,b)=>+new Date(b.date)-+new Date(a.date)),total=d.reduce((n,x)=>n+Number(x.amount_cents||0),0);const {recovery_birth_cipher,recovery_grand_cipher,...safe}=u;return {...safe,recovery_birth:await reveal(recovery_birth_cipher),recovery_grandfather:await reveal(recovery_grand_cipher),total_spent_cents:total,purchases:d,purchase_count:d.length}}));rows.sort((a:any,b:any)=>b.total_spent_cents-a.total_spent_cents||+new Date(b.created_at)-+new Date(a.created_at));
const {data:logs}=await s.from('account_audit').select('username,actor,action,created_at').order('created_at',{ascending:false}).limit(200);
return json({users:rows,account_events:logs||[],total_users:rows.length,total_spent_cents:rows.reduce((n:any,x:any)=>n+x.total_spent_cents,0)})}
if(req.method==='DELETE'||req.method==='POST'){const b=await req.json().catch(()=>({}));
if(b.action==='delete'&&b.user_id){const {data:u}=await s.from('egg_users').select('id,username,email').eq('id',b.user_id).maybeSingle();if(!u)return json({error:'Usuário não encontrado.'},404);const {data:jobs}=await s.from('generator_jobs').select('pdf_path').eq('user_id',u.id);for(const table of ['super_inventory','super_purchases','simple_game_scores','game_activity_events','course_events']){const {error:cleanup}=await s.from(table).delete().eq('user_id',u.id);if(cleanup)throw cleanup}await audit(s,u,'account_deleted');const {error}=await s.from('egg_users').delete().eq('id',b.user_id);if(error)throw error;const paths=(jobs||[]).map((j:any)=>j.pdf_path).filter(Boolean);if(paths.length)await s.storage.from('product-files').remove(paths);return json({ok:true,deleted:u})}
if(b.action==='update'&&b.user_id){const {data:u}=await s.from('egg_users').select('id,username,email,full_name').eq('id',b.user_id).maybeSingle();if(!u)return json({error:'Usuário não encontrado.'},404);const username=String(b.username??u.username).trim().toLowerCase(),email=String(b.email??u.email??'').trim().toLowerCase(),password=String(b.password||'');if(!/^[a-z0-9_.-]{3,24}$/.test(username))return json({error:'Use um usuário de 3 a 24 caracteres: letras, números, ponto, traço ou _.'},400);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>160)return json({error:'Informe um e-mail válido.'},400);const [{data:eu},{data:ee}]=await Promise.all([s.from('egg_users').select('id').eq('username',username).neq('id',u.id).maybeSingle(),s.from('egg_users').select('id').ilike('email',email).neq('id',u.id).maybeSingle()]);if(eu)return json({error:'Esse nome de usuário já existe.'},409);if(ee)return json({error:'Esse e-mail já está cadastrado.'},409);const full_name=String(b.full_name??u.full_name??'').trim().replace(/\s+/g,' ');if(full_name&&(full_name.length<3||full_name.length>140||!full_name.includes(' ')))return json({error:'Informe o nome completo.'},400);const patch:any={username,email,full_name};if(password){if(password.length<6||password.length>72)return json({error:'A senha deve ter de 6 a 72 caracteres.'},400);const salt=crypto.randomUUID()+crypto.randomUUID();patch.password_salt=salt;patch.password_hash=await passHash(password,salt)}const {data:updated,error}=await s.from('egg_users').update(patch).eq('id',u.id).select('id,username,email,full_name,created_at,last_seen_at').single();if(error)throw error;if(password)await s.from('egg_sessions').delete().eq('user_id',u.id);await audit(s,u,password?'password_changed':'account_updated');return json({ok:true,user:updated,password_changed:!!password})}
return json({error:'Operação inválida.'},400)}
return json({error:'Método não permitido.'},405)}catch(e){console.error(e);const auth=String((e as any)?.message)==='AUTH';return json({error:auth?'Acesso não autorizado.':'Falha ao administrar usuários.'},auth?401:500)}});
