import {createClient} from 'jsr:@supabase/supabase-js@2.116.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-egg-token','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const S=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const enc=new TextEncoder(),dec=new TextDecoder(),hex=(a:ArrayBuffer)=>[...new Uint8Array(a)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha(v:string){return hex(await crypto.subtle.digest('SHA-256',enc.encode(v)))}
async function passHash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:160000},key,256))}
const same=(a:string,b:string)=>{if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0};
const norm=(x:any)=>String(x||'').trim().toLocaleLowerCase('pt-BR');
const fullName=(x:any)=>String(x||'').trim().replace(/\s+/g,' ');
const birth=(x:any)=>{const v=String(x||'').trim();if(!/^\d{8}$/.test(v))return '';const d=+v.slice(0,2),m=+v.slice(2,4),y=+v.slice(4);const dt=new Date(Date.UTC(y,m-1,d));return dt.getUTCFullYear()===y&&dt.getUTCMonth()===m-1&&dt.getUTCDate()===d&&y>1900&&y<=new Date().getUTCFullYear()?v:''};
const grand=(x:any)=>{const v=norm(x);return /^[\p{L}]{2,40}$/u.test(v)?v:''};
const cleanName=(x:any)=>{const v=fullName(x);return v.length>=3&&v.length<=140&&v.includes(' ')?v:''};
async function cipherKey(){const raw=await crypto.subtle.digest('SHA-256',enc.encode('dominael-recovery-v1:'+Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')));return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt'])}
const b64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes));
async function seal(value:string){const iv=crypto.getRandomValues(new Uint8Array(12)),data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await cipherKey(),enc.encode(value)));return b64(iv)+'.'+b64(data)}
async function unseal(value:string){if(!value)return '';const [a,b]=value.split('.');const iv=Uint8Array.from(atob(a),c=>c.charCodeAt(0)),data=Uint8Array.from(atob(b),c=>c.charCodeAt(0));return dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},await cipherKey(),data))}
const SESSION_DAYS=365,RENEW_BEFORE_DAYS=90;
async function sessionFor(s:any,token:string){if(!token)return null;const h=await sha(token),{data:ss}=await s.from('egg_sessions').select('user_id,expires_at').eq('token_hash',h).maybeSingle();if(!ss||new Date(ss.expires_at)<=new Date()){if(ss)await s.from('egg_sessions').delete().eq('token_hash',h);return null}if(new Date(ss.expires_at).getTime()-Date.now()<RENEW_BEFORE_DAYS*86400000)await s.from('egg_sessions').update({expires_at:new Date(Date.now()+SESSION_DAYS*86400000).toISOString()}).eq('token_hash',h);const {data:u}=await s.from('egg_users').select('*').eq('id',ss.user_id).maybeSingle();return u||null}
async function newSession(s:any,user_id:string){const raw=hex(crypto.getRandomValues(new Uint8Array(32)).buffer),h=await sha(raw),exp=new Date(Date.now()+SESSION_DAYS*86400000).toISOString();const {error}=await s.from('egg_sessions').insert({token_hash:h,user_id,expires_at:exp});if(error)throw error;return{token:raw,expires_at:exp}}
const publicUser=(u:any)=>({id:u.id,username:u.username,email:u.email,full_name:u.full_name||'',recovery_configured:!!u.recovery_birth_hash});
async function audit(s:any,u:any,actor:string,action:string){const {error}=await s.from('account_audit').insert({user_id:u.id,username:u.username,actor,action});if(error)throw error}
async function answerPatch(b:any){const date=birth(b.birth),name=grand(b.grandfather);if(!date||!name)return null;const salt=crypto.randomUUID()+crypto.randomUUID();return {recovery_salt:salt,recovery_birth_hash:await passHash(date,salt),recovery_grand_hash:await passHash(name,salt),recovery_birth_cipher:await seal(date),recovery_grand_cipher:await seal(name)}}
const pw=(v:any)=>typeof v==='string'&&v.length>=6&&v.length<=72;
const invalid='Não foi possível confirmar os dados de recuperação.';
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const s=S(),token=req.headers.get('x-egg-token')||'';
if(req.method==='GET'){const u=await sessionFor(s,token);if(!u)return json({authenticated:false},401);const account=new URL(req.url).searchParams.get('mode')==='account';return json({authenticated:true,user:publicUser(u),...(account?{recovery:{birth:await unseal(u.recovery_birth_cipher),grandfather:await unseal(u.recovery_grand_cipher)}}:{})})}
if(req.method!=='POST')return json({error:'Método não permitido.'},405);const b=await req.json(),action=String(b.action||'');
if(action==='register'){const username=norm(b.username),email=norm(b.email),password=String(b.password||''),name=cleanName(b.full_name),answers=await answerPatch(b);if(!/^[a-z0-9_.-]{3,24}$/.test(username))return json({error:'Use um usuário de 3 a 24 caracteres: letras, números, ponto, traço ou _.'},400);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>160)return json({error:'Informe um e-mail válido.'},400);if(!pw(password))return json({error:'A senha deve ter de 6 a 72 caracteres.'},400);if(!name)return json({error:'Informe seu nome completo.'},400);if(!answers)return json({error:'Informe a data em DDMMAAAA e apenas o primeiro nome do avô, sem espaços nem pontuação.'},400);const [{data:eu},{data:ee}]=await Promise.all([s.from('egg_users').select('id').eq('username',username).maybeSingle(),s.from('egg_users').select('id').ilike('email',email).maybeSingle()]);if(eu)return json({error:'Esse usuário já existe.'},409);if(ee)return json({error:'Esse e-mail já está cadastrado.'},409);const salt=crypto.randomUUID()+crypto.randomUUID(),password_hash=await passHash(password,salt);const {data:u,error}=await s.from('egg_users').insert({username,email,full_name:name,password_salt:salt,password_hash,...answers}).select('*').single();if(error)throw error;await s.from('egg_state').insert({user_id:u.id});const ss=await newSession(s,u.id);await audit(s,u,'user','registered');return json({authenticated:true,user:publicUser(u),...ss},201)}
if(action==='login'){const login=norm(b.username||b.login),password=String(b.password||'');let q=s.from('egg_users').select('*');q=login.includes('@')?q.ilike('email',login):q.eq('username',login);const {data:u}=await q.maybeSingle();if(!u)return json({error:'Usuário/e-mail ou senha inválidos.'},401);const h=await passHash(password,u.password_salt);if(!same(h,u.password_hash))return json({error:'Usuário/e-mail ou senha inválidos.'},401);const ss=await newSession(s,u.id);return json({authenticated:true,user:publicUser(u),...ss})}
if(action==='recover'){const login=norm(b.username||b.login),date=birth(b.birth),name=grand(b.grandfather),password=String(b.new_password||'');if(!pw(password)||!date||!name||!login)return json({error:invalid},400);let q=s.from('egg_users').select('*');q=login.includes('@')?q.ilike('email',login):q.eq('username',login);const {data:u}=await q.maybeSingle();if(!u||!u.recovery_salt)return json({error:invalid},400);const {data:a}=await s.from('account_recovery_attempts').select('attempts,window_start').eq('user_id',u.id).maybeSingle();const active=a&&Date.now()-new Date(a.window_start).getTime()<86400000,count=active?a.attempts:0;if(count>=5)return json({error:'Limite de tentativas atingido. Tente novamente em até 24 horas ou fale com o suporte.'},429);const {error:attemptError}=await s.from('account_recovery_attempts').upsert({user_id:u.id,attempts:count+1,window_start:active?a.window_start:new Date().toISOString()});if(attemptError)throw attemptError;const [dh,gh]=await Promise.all([passHash(date,u.recovery_salt),passHash(name,u.recovery_salt)]);if(!same(dh,u.recovery_birth_hash)||!same(gh,u.recovery_grand_hash))return json({error:invalid},400);const salt=crypto.randomUUID()+crypto.randomUUID(),password_hash=await passHash(password,salt);const {error}=await s.from('egg_users').update({password_salt:salt,password_hash}).eq('id',u.id);if(error)throw error;await s.from('egg_sessions').delete().eq('user_id',u.id);await s.from('account_recovery_attempts').delete().eq('user_id',u.id);await audit(s,u,'user','password_recovered');return json({ok:true,message:'Senha alterada. Entre com a nova senha.'})}
const u=await sessionFor(s,token);if(!u)return json({error:'Entre na sua conta.'},401);
if(action==='set_email'){const email=norm(b.email);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:'Informe um e-mail válido.'},400);const {data:e}=await s.from('egg_users').select('id').ilike('email',email).neq('id',u.id).maybeSingle();if(e)return json({error:'Esse e-mail já está cadastrado.'},409);const {error}=await s.from('egg_users').update({email}).eq('id',u.id);if(error)throw error;await audit(s,u,'user','email_changed');return json({ok:true,email})}
if(action==='set_recovery'){if(u.recovery_salt)return json({error:'As respostas já foram definidas e não podem ser alteradas.'},409);const old=await passHash(String(b.password||''),u.password_salt);if(!same(old,u.password_hash))return json({error:'Senha atual incorreta.'},401);const name=cleanName(b.full_name),answers=await answerPatch(b);if(!name||!answers)return json({error:'Preencha nome completo e as duas respostas no formato indicado.'},400);const {error}=await s.from('egg_users').update({full_name:name,...answers}).eq('id',u.id);if(error)throw error;await audit(s,u,'user','recovery_configured');return json({ok:true})}
if(action==='change_password'){if(!pw(b.new_password))return json({error:'A nova senha deve ter de 6 a 72 caracteres.'},400);const h=await passHash(String(b.old_password||''),u.password_salt);if(!same(h,u.password_hash))return json({error:'Senha atual incorreta.'},401);const salt=crypto.randomUUID()+crypto.randomUUID(),password_hash=await passHash(b.new_password,salt);const {error}=await s.from('egg_users').update({password_salt:salt,password_hash}).eq('id',u.id);if(error)throw error;await s.from('egg_sessions').delete().eq('user_id',u.id);await audit(s,u,'user','password_changed');return json({ok:true})}
if(action==='delete_account'){const h=await passHash(String(b.password||''),u.password_salt);if(!same(h,u.password_hash)||String(b.confirm||'')!==u.username)return json({error:'Confirme seu usuário e sua senha atual.'},401);const {data:jobs}=await s.from('generator_jobs').select('pdf_path').eq('user_id',u.id);await audit(s,u,'user','account_deleted');const {error}=await s.from('egg_users').delete().eq('id',u.id);if(error)throw error;const paths=(jobs||[]).map((j:any)=>j.pdf_path).filter(Boolean);if(paths.length)await s.storage.from('product-files').remove(paths);return json({ok:true})}
if(action==='logout'){await s.from('egg_sessions').delete().eq('token_hash',await sha(token));return json({ok:true})}return json({error:'Ação inválida.'},400)
}catch(e){console.error(e);return json({error:'Não foi possível concluir o acesso.'},500)}});
